<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FactorK.KrestOne.Service.Application\FactorK.KrestOne.Service.Application.csproj" />
    <ProjectReference Include="..\FactorK.KrestOne.Service.Domain\FactorK.KrestOne.Service.Domain.csproj" />
  </ItemGroup>

</Project>
